### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by wemersonjanuario** [barbushin/php-console-laravel#5]
Could you make it campatible with Laravel 5? thanks!

**Comment by barbushin** [comment]
I want to do that, but right now do not have free time... to much work. And I'm not so familiar with Laravel 5 :(

May be some of Laravel 5 users can do that?

**Comment by younes0** [comment]
In the mean time, you can use https://github.com/morrislaptop/LaravelFivePackageBridges
The bridge class for this package:
```php
class PhpConsoleServiceProvider extends \PhpConsole\Laravel\ServiceProvider {
    use LaravelFivePackageBridgeTrait;
}
```

**Comment by project-hub** [comment]
Tested and released https://github.com/barbushin/php-console-laravel/releases/tag/5.0

Laravel 4.* compatible version will be available in https://github.com/barbushin/php-console-laravel/releases/tag/1.2.1

Cheers!
