### ISSUE TITLE
Disabling library has no effect if someone is using a helper.

### ISSUE THREAD

**Issue by shashankkrjain** [barbushin/php-console-laravel#7]
If I disable the library in config, but I am using helper, then log messages are still logged in console.

Ideal behavior would be to log messages when library is enabled, but don't log and simply skip the messages if library is disabled. This will make moving from development to production very easy.

For example,

`PC::debug("Hello!");`

Should send log message to console when library is enabled, but should not do anything if its disabled.

**Comment by barbushin** [comment]
@shashankkrjain I don't have so much time to test it with Laravel. Could you please check if now everything works fine? But don't forget to run `composer update` because this fix depends on new php-console release `3.1.4`. Thank you!

**Comment by shashankkrjain** [comment]
Okay, I am checking this. Will get back to you

**Comment by shashankkrjain** [comment]
This works fine. Thanks for the fix :)

**Comment by barbushin** [comment]
That's great! I published release including this fix https://github.com/barbushin/php-console-laravel/releases/tag/5.1

Thanks for report! :+1:
